PRIVATE  lnALCA AS INTEGER
DEFINE CLASS RF AS Session OLEPUBLIC
	lnALCA =0	
	loFIELDS = ''
	loTYPES  = ''
	loLEN	=  ''
	PROC OpenDB(DBname AS String) AS Integer 
		
		THIS.lnALCA = SQLSTRINGCONNECT(DBname)
		RETURN THIS.LnALCA 
	ENDPROC
	
	PROC DisconnectDB 
		IF THIS.LNALCA >0
			SQLDISCONNECT(THIS.LNALCA)
			THIS.LNALCA=0
		ENDIF
	ENDPROC

	HIDDEN PROCEDURE MAKEARRAY(Tablename AS String)
		LOCAL LNCAMPOS AS Integer
		LOCAL RETORNO,RETORNO2,RETORNO3 AS String
		STORE '' TO RETORNO,RETORNO2,RETORNO3
	  	DIMENSION laFIELDS[1] AS String
	  	
		IF EMPTY(Tablename) OR TYPE('Tablename') <> 'C' OR THIS.lnALCA < 0
			RETURN .F.
		ENDIF

		=SQLEXEC(THIS.LNALCA,'SELECT * FROM ' + ALLTRIM(Tablename) + ' WHERE 1=2','TMPFIELDS')
		
		SELE TMPFIELDS
		LNCAMPOS =AFIELDS(laFIELDS,'TMPFIELDS')
		LOCAL LNXI AS Integer
		FOR lnXI=1 TO LNCAMPOS 
			RETORNO = RETORNO + (laFIELDS[LNXI,1]) + ','
			RETORNO2 = RETORNO2 + (laFIELDS[LNXI,2]) + ','
			RETORNO3 = RETORNO3 + TRANSFORM((laFIELDS[LNXI,3])) + ','
			=ADDPROPERTY(this.loFIELDS,'FIELD_'+transform(LNxi),laFIELDS[LNXI,1])
			=ADDPROPERTY(this.lotypes,'FIELD_'+transform(LNxi),laFIELDS[LNXI,2])
			=ADDPROPERTY(this.lolen,'FIELD_'+transform(LNxi),laFIELDS[LNXI,3])
		NEXT
		RETURN '{' + RETORNO + '}{' + RETORNO2 + '}{' + RETORNO3 + '}'
	ENDPROC
	 	
	PROC ReturnFieldName(Tablename AS String,COMPLETEINFO AS Boolean) AS String
		LOCAL CAMPOS,TIPOS,TAM,RETORNO AS String 
		RETORNO 	= THIS.MAKEARRAY(Tablename)
		
		TIPOS	= ','+STREXTRACT(RETORNO ,'{','}',2)+','
		TAM		= ','+STREXTRACT(RETORNO ,'{','}',3)+','
		CAMPOS	= ','+STREXTRACT(RETORNO ,'{','}',1)+','
		RETORNO = ''
		
		IF EMPTY(COMPLETEINFO)
			COMPLETEINFO=.F.
		ENDIF
		
		LOCAL LNXI AS Integer
		IF COMPLETEINFO 
			FOR lnXI = 1 TO OCCURS(',',CAMPOS)-2
				RETORNO = RETORNO + STREXTRACT(CAMPOS,',',',',lnXI) + ' ' + STREXTRACT(TIPOS,',',',',lnXI) + ;
																		' ' + STREXTRACT(TAM,',',',',lnXI) + ','
			ENDFOR
		ELSE	
			FOR lnXI = 1 TO OCCURS(',',CAMPOS)-2
				RETORNO = RETORNO + STREXTRACT(CAMPOS,',',',',lnXI) + ','
			ENDFOR
		ENDIF
		RETURN RETORNO 
	ENDPROC
	
	PROC ReturnFieldNameXML(Tablename AS String,COMPLETEINFO AS Boolean) AS String 

		LOCAL CAMPOS,TIPOS,TAM,RETORNO AS String
		RETORNO 	= THIS.MAKEARRAY(Tablename)
		
		TIPOS	= ','+STREXTRACT(RETORNO ,'{','}',2)+','
		TAM		= ','+STREXTRACT(RETORNO ,'{','}',3)+','
		CAMPOS	= ','+STREXTRACT(RETORNO ,'{','}',1)+','
		RETORNO = '<?xml version="1.0" ?>' + CHR(13)
		
		IF EMPTY(COMPLETEINFO)
			COMPLETEINFO=.F.
		ENDIF
		
		LOCAL LNXI AS Integer
		IF COMPLETEINFO 
			RETORNO = RETORNO + '<' +tablename +'>' +  CHR(13)
			FOR lnXI = 1 TO OCCURS(',',CAMPOS)-2
				RETORNO = RETORNO + CHR(9) + '<FIELD'+TRANSFORM(lnXI)+'>' + CHR(13)+ REPLICATE(CHR(9),2) + '<NAME>' +;
				 STREXTRACT(CAMPOS,',',',',lnXI) +  '</NAME>'+  CHR(13) + REPLICATE(CHR(9),2) +'<TYPE>' +;
				 STREXTRACT(TIPOS,',',',',lnXI)	 +  '</TYPE>'+ CHR(13)+REPLICATE(CHR(9),2) +'<LEN>'	+;
				 STREXTRACT(TAM,',',',',lnXI)	 +	'</LEN>' + CHR(13) +CHR(9) +;
				 '</FIELD'+TRANSFORM(lnXI)+'>' + CHR(13)
			ENDFOR
			RETORNO = RETORNO + '</' +tablename +'>'
		ELSE	
			LORETORNO = LORETORNO + '<' +tablename +'>'
			FOR lnXI = 1 TO OCCURS(',',CAMPOS)-2
				RETORNO = RETORNO + CHR(9) + '<'+TRANSFORM(lnXI)+'>' + STREXTRACT(CAMPOS,',',',',lnXI) + '</'+TRANSFORM(lnXI)+'>' + CHR(13)
			ENDFOR
			RETORNO = RETORNO + '</' +tablename +'>'
		ENDIF
		RETURN RETORNO 
	
	ENDPROC
	
	PROC ReturnFieldNameTAB(Tablename AS String,COMPLETEINFO AS Boolean) AS String
		LOCAL CAMPOS,TIPOS,TAM,RETORNO AS String
		RETORNO 	= THIS.MAKEARRAY(Tablename)
		
		TIPOS	= ','+STREXTRACT(RETORNO ,'{','}',2)+','
		TAM		= ','+STREXTRACT(RETORNO ,'{','}',3)+','
		CAMPOS	= ','+STREXTRACT(RETORNO ,'{','}',1)+','
		RETORNO = ''
		
		
		IF EMPTY(COMPLETEINFO)
			COMPLETEINFO=.F.
		ENDIF
		
		LOCAL LNXI AS Integer
		IF COMPLETEINFO 
			RETORNO = 'NAME	TYPE	LEN' +  CHR(13)
			FOR lnXI = 1 TO OCCURS(',',CAMPOS)-2
				RETORNO = RETORNO + STREXTRACT(CAMPOS,',',',',lnXI) + CHR(9) +  STREXTRACT(TIPOS,',',',',lnXI) + CHR(9) +;
																		 STREXTRACT(TAM,',',',',lnXI) + CHR(13)
			ENDFOR
		ELSE	
			FOR lnXI = 1 TO OCCURS(',',CAMPOS)-2
				RETORNO = RETORNO + STREXTRACT(CAMPOS,',',',',lnXI) + CHR(13)
			ENDFOR
		ENDIF
		RETURN RETORNO 
		
	ENDPROC
	
	
	PROC INIT
		CLEAR PROGRAM
		this.loFIELDS = CREATEOBJECT('empty')
		THIS.LOTYPES  =	CREATEOBJECT('empty')
		this.loLEN	  =	CREATEOBJECT('empty')
	ENDPROC
	
	PROC DESTROY
		THIS.DisconnectDB()
		CLEAR PROGRAM 
		RELEASE ALL
		CLOSE ALL
		CANCEL
		QUIT
	ENDPROC
	

ENDDEFINE